### ISSUE TITLE
getting "listen is undefined" error when working with redux-router's new history object

### ISSUE THREAD

**Issue by mfhholmes** [rackt/redux-simple-router#173] opened 2016-01-07 15:47 UTC
it doesn't appear to have a listen method

**Comment by mfhholmes** [comment] 2016-01-07 15:48
apologies, too tired to make much sense. I got it working vaguely by explicitly depending on history and creating a new browserHistory to seed into SyncReduxAndRouter. But it leaves hashes all over the url :(

**Comment by kjbekkelund** [comment] 2016-01-07 18:10
Without a reproducible example we have no way of helping you. Quite a few of us use this already, so without code it's difficult to say what the problem is with your setup.

I'll close this for now, but let's re-open this when you add an example we can look at :)

**Closed by kjbekkelund** 2016-01-07 18:10 UTC

**Comment by mfhholmes** [comment] 2016-01-08 02:40
my sincere apologies. way too tired to be thinking straight. I had the wrong react-router version, which didn't have a history, and therefore didn't have listen. So easy to resolve once I'd slept ;)

thanks for the awesome work, keep it up :)

**Comment by stonecobra** [comment] 2016-01-21 23:23
I am actually having this problem with react-router@2.0.0rc4.  Issue is that browserHistory returns undefined on serverside:

https://github.com/rackt/react-router/blob/v2.0.0-rc4/modules/browserHistory.js#L8

So, I assume redux-simple-router should either guard against that, or should I just not load the middleware when server side?

**Comment by timdorr** [comment] 2016-01-22 01:39
You should pass it a memory history that you create yourself. We also [export a `createMemoryHistory` function](https://github.com/rackt/react-router/blob/master/modules/index.js#L30) that you can use.
