### ISSUE TITLE
history.goBack()

### ISSUE THREAD

**Issue by acnovais** [rackt/redux-simple-router#126] opened 2015-12-18 16:16 UTC
Hey Guys,

I am using a `MemoryHistory` and I would like to execute a `goBack()` with the router. Do you have any suggestions on how to do this?

Thanks

**Comment by kjbekkelund** [comment] 2015-12-18 16:58
Are you seeing bugs or problems with redux-simple-router? Not sure I understand what you need

**Comment by kjbekkelund** [comment] 2015-12-18 18:22
Ah, now with #127 I think I understand what you mean. I would suggest just using `history` directly.

**Comment by jlongster** [comment] 2015-12-18 20:59
Closing as a dupe of #127

**Closed by jlongster** 2015-12-18 20:59 UTC
