### ISSUE TITLE
use es6  the reducer bind bug on examples and README.md

### ISSUE THREAD

**Issue by xingyesh** [rackt/redux-simple-router#172] opened 2016-01-07 03:08 UTC
```javascript
import reducers from '<project-path>/reducers'

const reducer = combineReducers(Object.assign({}, reducers, {
  routing: routeReducer
}))
```
It did not bind the reducers.
The correct code :
```javascript
import reducers from '<project-path>/reducers'

const reducer = combineReducers(Object.assign({}, reducers, {
  routing: routeReducer,
  reducers
}))
```

**Comment by kjbekkelund** [comment] 2016-01-07 18:14
Do you have a reproducible example? The first one should work fine.

```
var obj = Object.assign({}, { a: 'foo' }, { b: 'bar' });
console.log(obj); // { a: 'foo', b: 'bar' }
```

I'll just close this now, and re-open if you add a reproducible example :)

If you can get this to run in your setup, we need more code to understand what the problem is.

**Closed by kjbekkelund** 2016-01-07 18:14 UTC

**Comment by xingyesh** [comment] 2016-01-10 10:14
OK,I got it.
