### ISSUE TITLE
Implement in react-redux-universal-hot-example

### ISSUE THREAD

**Issue by quicksnap** [rackt/redux-simple-router#13] opened 2015-11-10 02:24 UTC
There's some talk about this library in https://github.com/erikras/react-redux-universal-hot-example/issues/439

Would you be interested in starting a branch to integrate this library as a replacement? It could serve as a good example on how to migrate from redux-router to redux-simple-router, and could uncover pain points along the way.

I'd be happy to help, too. But for the next few days, probably not much.

If you think it would not serve as a good replacement, that would be great information, too!

**Comment by jlongster** [comment] 2015-11-10 14:57
That would be an interesting experiment, and I'm sure I'd learn a few things about why redux-router works the way it does. I don't think I'll have time to do it in the next few days (not really familiar with it) but I'll keep this issue open and maybe next week I can take a shot.

**Comment by quicksnap** [comment] 2015-11-10 23:06
Totally--I'm interested too, but pretty busy myself. I haven't personally run into any issues with redux-router in my project, so it's low priority for my own needs.

**Comment by jlongster** [comment] 2015-11-11 04:31
Alright, I did an initial port here: https://github.com/jlongster/react-redux-universal-hot-example/commit/e13b93518c8c9b5524ad50f1c566ed6c480c1888?diff=split

Who else should I loop in? @stevoland @erikras @justingreenberg? I'll play around with it for a few more days.

It's more elegant IMHO. Particularly server-rendering. No more hacks to store the data fetching promise on the state or anything like that. The state should stay pure. You can just use react-router straight up.

**Comment by quicksnap** [comment] 2015-11-11 08:51
Looks good at first glance--thanks for doing this!

I'll try and take a look tomorrow and port it into my project.

**Comment by justingreenberg** [comment] 2015-11-11 15:51
@jlongster thank you so much for taking the time to put this together! i'll review in more detail this afternoon and let you know if i have any questions or other feedback :smile:

**Comment by bendiy** [comment] 2015-11-11 17:58
@jlongster Thanks for putting this together so quickly. I was struggling with `redux-router` and this approach seems much simpler.

I found a small change here:
https://github.com/jlongster/react-redux-universal-hot-example/commit/e13b93518c8c9b5524ad50f1c566ed6c480c1888?diff=split#commitcomment-14335312

**Comment by Dattaya** [comment] 2015-11-11 18:20
@jlongster dispatching during this stage gave me this warning on the client while transitioning: `Warning: setState(...): Cannot update during an existing state transition (such as within render). Render methods should be a pure function of props and state.` What about you, did you test the code?

**Comment by erikras** [comment] 2015-11-11 18:33
If you guys could kick the tires on this a bit more, I'd love to merge it.

**Comment by quicksnap** [comment] 2015-11-11 21:09
I definitely think we should test this out for about a week before merging, just to make sure! But looks great.

**Comment by jlongster** [comment] 2015-11-12 21:46
Will kick around some more soon, been a busy week at work. @Dattaya thanks for the report.

**Comment by louissmit** [comment] 2015-11-13 14:01
I think ```fetchDataDeferred``` stopped working in @jlongster 's port? Like when you route to /widgets

**Comment by stevoland** [comment] 2015-11-13 14:14
@louissmit I think `fetchData` becomes the equivalent of `fetchDataDeferred` as it no longer blocks rendering of the container: https://github.com/jlongster/react-redux-universal-hot-example/commit/e13b93518c8c9b5524ad50f1c566ed6c480c1888?diff=split#diff-cf27c1d543e886c89cd9ac8b8aeaf05bR39 This is fine as far as I'm concerned.

Looks great! I'm starting a project right now and this is going in for sure.

**Comment by louissmit** [comment] 2015-11-13 15:21
@stevoland I'm not sure I see how it no longer blocks, but in either case the widgets example is broken in its current implementation. 

I'm new to this boilerplate and redux so I'm just trying to figure out how it works. (:

**Comment by jlongster** [comment] 2015-11-13 15:25
@louissmit haven't had a chance to flesh all this out yet, this week has been busy. I'm going to work on it some this weekend.

On the client-side, it does not blog, but that's just the strategy I chose for now. It we want it to block to emulate the previous behavior, we just need to use `onEnter` which has a 3rd `callback` argument.

**Comment by quicksnap** [comment] 2015-11-13 21:18
Glad to hear @stevoland likes this! I think I'll have some time today to try it. My project relies on both fetchData and fetchDataDeferred, so if I can get it working I'd be stoked!

**Comment by Dattaya** [comment] 2015-11-13 21:31
Dispatching in createElement might not be a good way of doing things. @timdorr hasn't written anything here yet (I asked him to give some advice), but this is what he recommended, how he implemented data pre-fetch on the client https://gist.github.com/timdorr/3ffe30e3c4e116019bc3 this is one way to implement `fetchDataDeferred`, not sure about `fetchData` on the client.

**Comment by timdorr** [comment] 2015-11-13 21:40
Note that there are a few libraries out there for the exact same thing, such as [`react-fetcher`](https://github.com/markdalgleish/react-fetcher) and [`react-resolver`](https://github.com/ericclemmons/react-resolver).

**Comment by justingreenberg** [comment] 2015-11-13 21:45
thanks @timdorr i hadn't seen [markdalgleish/react-fetcher](https://github.com/markdalgleish/react-fetcher), looks like a good fit for react-redux-universal-hot-example

**Comment by timdorr** [comment] 2015-11-13 21:53
The biggest thing `react-fetcher` needs is the ability to also run on `componentDidMount`, so you don't have to duplicate your fetching logic when mounting a component (such as when entering a route) inside of each component. Other than that, it's a pretty good start for a 0.2.0 version.

**Comment by quicksnap** [comment] 2015-11-14 01:21
Just gave it a whirl:

- I am aslo getting the `setState()` warnings during transition. 
- Before we merge, I feel there should be a good pattern for a route-blocking `fetchData`. There are good use cases for it.

I'm not sure where the `setState` bug is. I may have some time to investigate later.

**Comment by quicksnap** [comment] 2015-11-14 01:24
More information: the `setState()` is being called within `@connect`, which is being called from `RoutingContext` `render()`.

Per the warning, `setState` within `render` is bad.

**Comment by quicksnap** [comment] 2015-11-14 01:31
As a hack, wrap `fetchData` in a timeout: https://github.com/jlongster/react-redux-universal-hot-example/pull/2/files#diff-cf27c1d543e886c89cd9ac8b8aeaf05bR41

**Comment by quicksnap** [comment] 2015-11-14 01:37
As for the issue with blocking route transitions, would it be sensible to create a `Route` HOC that checks for a static method within `onEnter`

**Comment by markdalgleish** [comment] 2015-11-14 08:25
@timdorr `react-fetcher` is a relatively small library, and it doesn't place any restrictions on when you can fetch data. There's no reason you couldn't do it on `componentDidMount` if you want. In fact, v0.2.0 was released in anticipation of making this use case easier by allowing data fetching for a single component, not just arrays of components.

**Comment by sompylasar** [comment] 2015-11-15 18:23
@jlongster there are a couple of serious errors in the example implementation, please see my comments:
https://github.com/jlongster/react-redux-universal-hot-example/commit/e13b93518c8c9b5524ad50f1c566ed6c480c1888?diff=split#commitcomment-14403049
https://github.com/jlongster/react-redux-universal-hot-example/commit/e13b93518c8c9b5524ad50f1c566ed6c480c1888?diff=split#commitcomment-14403070

**Comment by oyeanuj** [comment] 2015-11-23 15:35
As someone who was enthusiastically following the redux-router vs redux-simple-router debate, just checking in if there are any updates here? :)

**Comment by jlongster** [comment] 2015-11-23 15:56
I've been moving forward slowly with this project because I really wanted to think some things though. This PR implements a very different way to sync route changes: https://github.com/jlongster/redux-simple-router/pull/40

It looks like that works well, and I still want to add a test suite to this project. I wanted to wait until this stabilizes a bit before fully porting that project. It will be soon though.

**Comment by glennr** [comment] 2015-11-30 07:52
@sompylasar - not sure if my question on https://github.com/jlongster/react-redux-universal-hot-example/commit/e13b93518c8c9b5524ad50f1c566ed6c480c1888?diff=split#commitcomment-14403070 will come through - so here it is - how do we reproduce the server-hang-on-rejected-promise issue. I had little luck reproducing it.

**Comment by glennr** [comment] 2015-11-30 08:04
And another issue not-related-to-this-project-but-to-jlongster/react-redux-universal-hot-example...

@quicksnap - re: the setState() issue - did you notice the same problem on the Chat component?

https://monosnap.com/file/ouGicqqm47vq3YIqiqT2aNYEsLgbFD.png

**Comment by sompylasar** [comment] 2015-11-30 11:23
@glennr replied there.

**Comment by quicksnap** [comment] 2015-11-30 18:13
@glennr I ran this in my own project based off the boilerplate, so Chat isn't present. However, the issue will be present in various states.

**Comment by Ghostavio** [comment] 2015-12-06 14:56
hey guys
how is the progress on this?

thanks :)

**Comment by tomatau** [comment] 2015-12-06 20:52
I have a universal boilerplate application that's working with redux-simple-router and koa. https://github.com/tomatau/breko-hub

The simple router integration takes place in `src/app/state/store.js`

Any criticism on the approach taken is more than welcome!

**Comment by capkutay** [comment] 2015-12-06 22:49
I also noticed Chat isn't in this version of the boilerplate. Is there a reason why it was excluded?

**Comment by bdefore** [comment] 2015-12-10 00:52
Not sure what the timeline is like for this, but I made a PR bringing much of this and its open pull requests into example project, along with universal-redux npm package. 

That PR is here: https://github.com/erikras/react-redux-universal-hot-example/pull/685

**Comment by mhahn** [comment] 2015-12-10 20:08
getting the setState error on the client as well:
```
Warning: setState(...): Cannot update during an existing state transition (such as within `render`). Render methods should be a pure function of props and state.```

**Comment by mhahn** [comment] 2015-12-10 22:02
I followed the structure you recommended for server side rendering, ie. if the component has a `fetchData` static method, which is called in a custom `createElement` function that gets passed to `Router`. One issue I'm running into is that the `fetchData` call will be executed before react life cycle methods.

Specifically, I have a search component that clears its cache within `componentWillUnmount`, lets call it component A. There is a scenario where we load another component (component B) which fetches search results in its `fetchData`.

what is happening now is:

as we transition from A to B:

- B's `fetchData` is called
- A's `componentWillUnmount` is called
- B's `componentWillMount` is called

this is breaking for me because `fetchData` thinks it has cached search results, which get cleared in `componentWillUnmount`.

If i fetch the results in component B's `componentWillMount` i'm triggering multiple search requests on the server side. It isn't a huge deal since only 1 hits the API since the subsequent one in componentWillMount uses the cache, but it is a little messy.

**Comment by mariocasciaro** [comment] 2015-12-17 10:01
Somebody might find it useful to take a look at the code in this PR as well as the associated discussion:  https://github.com/jlongster/react-redux-universal-hot-example/pull/4

**Comment by oyeanuj** [comment] 2015-12-31 16:40
As someone who was enthusiastically following the redux-simple-router, just checking in if there are any updates here and if it would play well with the react-router 2.0? :) @jlongster @mariocasciaro

**Comment by jlongster** [comment] 2015-12-31 16:57
We're working on a new API in #141 and just landed it. Basically we're still settling on the right solution so I'm not focusing on any template/boilerplate project yet until we've stabilized. I think what's on master might be pretty robust, but we'll see.

**Comment by timdorr** [comment] 2016-01-17 01:55
Is this still being pursued? 2.0 is out, so now's the time!

**Comment by bdefore** [comment] 2016-01-18 09:42
@timdorr I believe this issue would still be problematic for RRUHE: https://github.com/jlongster/react-redux-universal-hot-example/pull/4

I've managed to bring version 2.0.1 (and react-router 2.0.0-rc5) into universal-redux 3.0.0-rc7 (https://github.com/bdefore/universal-redux). It's working like a charm there using async-props rather than the serverside fetching mechanism of RRUHE.

**Comment by timdorr** [comment] 2016-01-20 03:09
I'm going to close this, as it can either be tracked on @jlongster's repo or the original. Either way, outside of specific fixes the library has to make (which would require issues here), there isn't really anything to do in this repo.

**Closed by timdorr** 2016-01-20 03:09 UTC

**Comment by Dattaya** [comment] 2016-01-26 20:22
I like proposed solutions to this problem. There is another one--bring back `universalRouter` (see [universalRouter](https://github.com/erikras/react-redux-universal-hot-example/blob/7b7608ee6c3ccfdaa34f3f0326ff78a5e3f542ef/src/helpers/universalRouter.js), [client.js](https://github.com/erikras/react-redux-universal-hot-example/blob/7b7608ee6c3ccfdaa34f3f0326ff78a5e3f542ef/src/client.js), [server.js](https://github.com/erikras/react-redux-universal-hot-example/blob/7b7608ee6c3ccfdaa34f3f0326ff78a5e3f542ef/src/server.js).)
It would be nice if someone knowledgeable about `react-router` and `history` advise us whether using `match` this way on the client is a good design or a hacky solution that can lead to bugs/complications in the future. 
I tried to improve it to handle errors identically. This is a basic idea: https://gist.github.com/Dattaya/191bc290ed1bc7855e33

Here're few potential benefits:
* symmetry between the client and the server which is an indication of a good design.
* it's relatively simple (66 lines of code)
* better error handling. For now it handles 5xx errors and for others returns 404 page. (it has a downside, [`preload` can't be set to `false`](https://github.com/Dattaya/isomorphic-redux-plus/blob/universal-router/client/index.js#L52))

If you want to see error handling in action, take a look at my repository https://github.com/Dattaya/isomorphic-redux-plus/tree/universal-router I use it because it's dead simple which means it's much easier to experiment with + hot-reloading is blazingly fast. 
[API is configured](https://github.com/Dattaya/isomorphic-redux-plus/blob/universal-router/api/api.js#L33) to return http error 500 if id === 5. Error page could be seen only in production, in the development mode [it just calls `reject`](https://github.com/Dattaya/isomorphic-redux-plus/blob/universal-router/shared/lib/universalRouter.js#L24) and prints error message to the console. 
Run `npm run build`, `npm start`. Open http://localhost:3000/todos. If you press on `Todo item 5`, you'll see an error page: `500 Internal Server Error Administrators have been notified. Please try again later.` If you load it directly http://localhost:3000/todos/5 , the server will respond with the same page; in addition the status of the page will be 500.

**Comment by quicksnap** [comment] 2016-01-27 18:53
Update on this: we have an experimental branch, `simple-router` here: https://github.com/erikras/react-redux-universal-hot-example/tree/simple-router

IMO, it's best to discuss ideas in RRUHE repo if it doesn't directly relate to react-router-redux so not to drain on the collaborators here.

**Comment by Dattaya** [comment] 2016-01-27 19:03
I'll open then a new issue in RRUHE sometime this week.
